version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  investment-api:
    restart: on-failure
    depends_on:
      - postgres
    build: ./src/Investment.App.Api
    ports:
      - "8080:8080"
