// <auto-generated />
using System;
using Investment.App.Api.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Investment.App.Api.Infrastructure.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    partial class InvestmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Investment.App.Api.Entities.CustomerInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinancialProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialPurchaseAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UpdatedPurchaseAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FinancialProductId");

                    b.ToTable("CustomerInvestments");
                });

            modelBuilder.Entity("Investment.App.Api.Entities.CustomerInvestmentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CustomerInvestmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerInvestmentId");

                    b.ToTable("CustomerInvestmentOperations");
                });

            modelBuilder.Entity("Investment.App.Api.Entities.FinancialProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MininumInvestment")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FinancialProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e90ec31a-2474-4116-bc26-6a702b450b85"),
                            Description = "CDB Loren Ipsun",
                            Enabled = true,
                            Expires = new DateTime(2024, 11, 23, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2458),
                            MininumInvestment = 50m,
                            Name = "CDB",
                            RiskLevel = 5,
                            TimeStamp = new DateTime(2024, 6, 23, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2468)
                        },
                        new
                        {
                            Id = new Guid("5314c8d1-77f8-4650-b60d-e759b8a082ab"),
                            Description = "LCI Loren Ipsun",
                            Enabled = true,
                            Expires = new DateTime(2024, 12, 23, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2471),
                            MininumInvestment = 500m,
                            Name = "LCI",
                            RiskLevel = 5,
                            TimeStamp = new DateTime(2024, 6, 23, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2472)
                        },
                        new
                        {
                            Id = new Guid("03d1c4ed-160c-47e3-8519-de0e37fc2fd7"),
                            Description = "LCA Loren Ipsun",
                            Enabled = true,
                            Expires = new DateTime(2024, 6, 29, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2623),
                            MininumInvestment = 1000m,
                            Name = "LCA",
                            RiskLevel = 5,
                            TimeStamp = new DateTime(2024, 6, 23, 2, 52, 6, 20, DateTimeKind.Utc).AddTicks(2639)
                        });
                });

            modelBuilder.Entity("Investment.App.Api.Entities.CustomerInvestment", b =>
                {
                    b.HasOne("Investment.App.Api.Entities.FinancialProduct", "FinancialProduct")
                        .WithMany("Investments")
                        .HasForeignKey("FinancialProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialProduct");
                });

            modelBuilder.Entity("Investment.App.Api.Entities.CustomerInvestmentOperation", b =>
                {
                    b.HasOne("Investment.App.Api.Entities.CustomerInvestment", "CustomerInvestment")
                        .WithMany("Operations")
                        .HasForeignKey("CustomerInvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerInvestment");
                });

            modelBuilder.Entity("Investment.App.Api.Entities.CustomerInvestment", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Investment.App.Api.Entities.FinancialProduct", b =>
                {
                    b.Navigation("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
